### PR TITLE
Swiss Flavour regarding Vorarlberg

### PR DESCRIPTION
**Pull request by Libeccio-DD**
In a referendum was held in Vorarlberg (in-game Bregenz) on 11 May 1919 and over 80% of those voting supported a proposal for the state to join the Swiss Confederation. Eventually because of Switzerland's lukewarm approach and Italy's insistence that the province remain part of Austria, Vorarlberg never joined the Confederation. 

However I created a couple of events that if Austria, Austira-Hungary or the Danubian Federation get dismantled in a Great War that give the opportunity to Vorarlberg to become part of Switzerland. The way it works is that a random GP that won the war against Austria gets an event that let's them decide whether they agree with the annexation or not and then Switzerland finally decides with the ai taking into consideration the GP's choice. Because historically the various religious and linguistic groups of Switzerland were either in favour or against incorporating Vorarberg, Switzerland's pops get either an increase or decrease of consciousness depending on their religion and the choice that was made in the event. 

I've changed the pops of Vorarlberg to Swiss as the referendum with its results clearly show how the people there saw their own cultural identity. In fact, it seems that those who voted against did so out of economic reasons rather than nationalistic.

I've also added Swiss as an accepted culture to AUS/KUK/DNB although I haven't found any evidence that they were hostile to the Austrian government but perhaps more importantly this will prevent the Swiss pops there from assimilating as there's no Swiss core at the start of the game. Accordingly I added an event that if AUS/KUK/DNB ever declare war on Switzerland, Swiss gets removed as an accepted culture.

There's a new decision as well that gives Switzerland cores to Vorarlberg if they have abandoned their neutrality or it got violated.

Finally even though I haven't renamed it, I strongly recommend renaming Bregenz to Vorarlberg to avoid confusing the player.

[https://en.wikipedia.org/wiki/Vorarlberg#History](url)

If these little additions to the game get included in your mod, perhaps in the future they could get further expanded. For example the reason why Italy didn't want Switzerland to annex Vorarlberg was because they saw an opportunity to get a bit of land themselves. They proposed to the Swiss that they can get Vorarlberg but only if the give up Ticino to the Italians. Ticino was the Catholic Italian-speaking canton of Switzerland. Something like that I found a little bit hard to implement properly without creating an unnecessarily huge amounts of events but it could be added.

vorarlberg1

### CODE REVIEW

**Comment by moretrim** [comment]
@Libeccio-DD it looks like your local changes were done on top of the master branch, which could cause some confusion when merging this PR. Could you rebase your work on top of the Development branch?

**Comment by Libeccio-DD** [comment]
@moretrim How do I do that?

**Comment by moretrim** [comment]
This may not be be the right forum to talk about git.

I had intended to submit rebased branches to your fork (one for your [#70](https://github.com/moretrim/Historical-Project-Mod/tree/rebased-Swiss-Flavour), one for your [#71](https://github.com/moretrim/Historical-Project-Mod/tree/rebased-Armenian-religion-correction), but it turns out you have recently advanced your local Development branch by one commit, too. That means I can't submit PRs against an appropriate target.

I suggest one of the following:

- rebase your own branches (my original suggestion)
- track this repo's Development branch (not yours!) somewhere so that I can show to you what rebased branches look like
- allow me to re-submit your work in separate PRs (these commits would still be authored with your identity)

It's also possible to merge your PRs as-is, but that's not up to me.

---

When rebasing your work I also noticed that many of your files contain mixed line endings. We don’t have to worry about that for now, I’m making a note of it here so that I don’t forget about it.

**Review by arkhometha — CHANGES_REQUESTED** [review]
Hi @Libeccio-DD, thanks for the pull request. Usually I skim through every pull: if the pull is small and I agree with everything, it goes on through. If I don't, well, it takes more time. Which is why this took so long.
This is the case here. I'm ok with idea of the event but not the implementation. The problem is:
1. Making the province in question Swiss.
- As there's no shared history (especially as a Swiss canton), despite the proximity, making pops there Swiss wouldn't make much sense.
1. Giving Swiss as accepted to Austria.
- The lack of shared history is also a problem here, but it would also allow Austria to conquer Switzerland without the Swiss becoming angry or very nationalistic about it. The Swiss culture also includes the french and italian-speaking parts of Switzerland and overall the cantons were keen on not being included in Germany.

Since the province in question is small and homogeneous, the solution I see is after a few years making the province flip culture to either Swiss or Austrian, depending on who owns it. That can simulate the shifting loyalty while also keeping, for a while, a desire to come back to the other side and doesn't add any accepted cultures for Switzerland or Austria. You can see an example of culture flipping here:
https://github.com/arkhometha/Historical-Project-Mod/blob/45fa31bc43eb52f3fdbec869a2f8457185d162c1/HPM/events/ENGFlavor.txt#L3339

**Comment by Libeccio-DD** [comment]
Hey @arkhometha, I've dealt with everything you asked.

**Review by arkhometha — APPROVED** [review]
Thanks for the changes @Libeccio-DD, everything looks good.

**Pull request merged**
