### PR TITLE
Cleaning up CSV localisation files (2nd try) and social icons fix

### PR DESCRIPTION
**Pull request by THGSCST**
CSV reduced to just 3 columns with the final character "x" in the last column. This resolves the mess of the various columns.

Unlike the previous attempt (see pull #98 )this time: no headers were added, no duplicates were removed, only columns removed to improve the review of changes.

Added correction to an error of mine, where I forgot to change the number of frames in pull # 83. Now the social icons are ok.

### CODE REVIEW

**Comment by moretrim** [comment]
:+1: Looks good to me. For the sake of being thorough I'll mention that the PR adds newlines at the ends of files that didn't have them, but that's fine by me.

@thiagodesacosta re: your previous PR, if are you comfortable enough with Git you can keep a PR open, re-do the branch however you want (even from scratch) on your end, and the Github PR will automatically reflect these changes. This is not to admonish you as closing & re-opening is entirely fine, I just thought you'd like to know the option exists.

**Review by arkhometha — CHANGES_REQUESTED** [review]
Hi @thiagodesacosta, thanks for the commit. Sorry about this but there's a conflict with `00_HPM_decisions.csv` from other pull request (or my own changes).
Do keep in mind that semicolons are also used as a separator for translations (e.g. `EVTNAME5002;Stanley Cup;Coupe Stanley;Stanley Cup;;Copa Stanley;;;;;;;;;x`) and having several later is their standard. While HPM is english-only, I don't know the effects of removing all semicolons on people that are playing with the game translated or even in the English game.

**Comment by THGSCST** [comment]
I tested the game in English and did not notice any problems.

In other languages, the game will crash. However, as you already said, the mod cannot be played in other languages anyway ​​due to the lack of translation.

One of the benefits of this change is that it makes all CSV valid for use as a data source. In this way, certain jobs can be done in an automated way: duplicates can be easily removed, strings can be organized in alphabetical order, CSV files can be merged and rearranged ...

**Comment by moretrim** [comment]
> In other languages, the game will crash.

I was going to make a remark about that, but just to be sure I tested something first. On the current `development` I cannot start HPM in German (with a clean map cache). The game starts fine without mods, with the text in German as expected. @arkhometha Is that intended?

If it cannot be helped, this PR does not worsen the situation.

> One of the benefits of this change is that it makes all CSV valid for use as a data source.

Setting the above situation aside, it should be possible to make all translation files valid CSV while still preserving all language columns. Right?

---

I'll also mention that adding unrelated commits to this PR is not ideal for review purposes.

**Comment by THGSCST** [comment]
> If it cannot be helped, this PR does not worsen the situation.

Since the game (in English) only loads the first and second columns, ignoring all the others, I don't see any drawbacks.

> Setting the above situation aside, it should be possible to make all translation files valid CSV while still preserving all language columns. Right?

About that, what you suggest to be done is just regularize all files in the "Paradox standard" of 14 columns. However, most columns will be blank because there is no defined use. This can be done, but it is not yet a valid CSV. A sequence of blank columns is ambiguous in CSV and can be interpreted in several ways and saved in different ways. Since this mod incorporates other mods, which were made by different people, this is the reason that explains why the mod localisation files are different between them.

> I'll also mention that adding unrelated commits to this PR is not ideal for review purposes.

I made a mistake. I was in a hurry and ended up selecting the wrong Branch.

**Comment by THGSCST** [comment]
Closing this pull since there are too many conflicts and the proposed changes are no longer mergeable.

**Pull request closed without merging**
